USE [master]
GO

/****** Object:  Database [italikaDB]    Script Date: 29/03/2021 11:12:15 p. m. ******/
CREATE DATABASE [italikaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'italikaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\italikaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'italikaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\italikaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [italikaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [italikaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [italikaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [italikaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [italikaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [italikaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [italikaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [italikaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [italikaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [italikaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [italikaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [italikaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [italikaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [italikaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [italikaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [italikaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [italikaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [italikaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [italikaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [italikaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [italikaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [italikaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [italikaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [italikaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [italikaDB] SET  MULTI_USER 
GO

ALTER DATABASE [italikaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [italikaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [italikaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [italikaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [italikaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [italikaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [italikaDB] SET  READ_WRITE 
GO


