USE[italikaDB]
/*||||	CREACION DEL CATALOGO TIPO DE PRODUCTO	||||*/
CREATE TABLE dbo.tipoProducto 
(
	Id			INT IDENTITY(1,1) NOT NULL,
	Nombre		VARCHAR(250) NOT NULL
	CONSTRAINT pkTipoProducto PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
/*||||	INSERT DE DATOS AL CATALOGO TOPO PRODUCTO	||||*/
INSERT INTO dbo.tipoProducto
(
	Nombre
)
VALUES('TRABAJO'),('DEPORTIVA'),('INFANTIL'),('MOTOCROSS'),('ELECTRICA')
/*||||	CREACIÓN DE TABLA PADRE DE PRODUCTOS	|||||*/
CREATE TABLE dbo.Productos
(
	idProducto			INT IDENTITY(1,1) NOT NULL, --- IDENTIFICADOR PARA EL PRODUCTO 
	SKU					VARCHAR(30) NOT NULL,
	fert				VARCHAR(30) NOT NULL,
	modelo				VARCHAR(30) NOT NULL,
	tipo				INT			NOT NULL,
	numeroSerie			VARCHAR(50)	NOT NULL,
	fechaAlta			DATETIME	NOT NULL
	CONSTRAINT pkProducto PRIMARY KEY CLUSTERED 
	(
		idProducto ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE dbo.Productos ADD  DEFAULT ((GETDATE())) FOR fechaAlta
GO
/*||||	INSERT DE DADOS EN LA TABLA PADRE PARA PRUEBA	||||*/
INSERT INTO dbo.Productos
(
	SKU,
	fert,
	modelo,
	tipo,
	numeroSerie
)
VALUES	('ZS60002F092355','KETS966','K250',1,'192847194'),
		('RB002132062258','UALR175','L150',2,'938452729'),
		('BB005155000153','MANES63','P100',3,'953427185'),
		('NQUS9667082591','NQUS966','M250',4,'873526938'),
		('LAQU5052966705','LAQU505','S150',5,'728263532')
/*|||||	CREACIÓN DE LA REFERENCIA	|||||*/
ALTER TABLE [dbo].[productos]  WITH NOCHECK ADD  CONSTRAINT [FK_Producto_TipoProducto] FOREIGN KEY([Tipo])
REFERENCES [dbo].[TipoProducto] ([Id])
ON UPDATE CASCADE
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Producto_TipoProducto]
GO

		
